package es.degrassi.core.sql;

import lombok.Getter;

@Getter
public enum KeyType {
  PRIMARY_KEY("PRIMARY KEY"),
  NOT_NULL("NOTNULL"),
  FOREING_KEY("FOREING KEY"),
  REFERENCES("REFERENCES"),
  NOTNULL("NOT NULL"),
  DEFAULT("DEFAULT"),
  UNSIGNED("UNSIGNED"),
  CONSTRAINT("CONSTRAINT"),
  UNIQUE("UNIQUE"),
  AUTOINCREMENT("AUTO_INCREMENT"),
  AUTOGENERATED("AUTO_GENERATED");

  private final String name;

  KeyType(String value) {
    this.name = value;
  }

}
